# Generated by Django 3.2 on 2021-04-28 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('CEP', models.CharField(max_length=8)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Created At')),
                ('script', models.FilePathField(default='', path='ferramentas/contents/')),
                ('htmlpath', models.FilePathField(path='ferramentas/contents/')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('emails', models.ManyToManyField(to='ferramentas.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('finish_date', models.DateField(default=datetime.date.today, verbose_name='Finish Date')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Created', max_length=12)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferramentas.emailcontent')),
                ('group_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferramentas.groupcontacts')),
            ],
        ),
    ]
