# Generated by Django 3.1.1 on 2021-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20210423_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluida', 'Concluida'), ('Cancelada', 'Cancelada')], default='Concluida', max_length=12),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Criada em'),
        ),
    ]
