# Generated by Django 3.1.1 on 2021-04-23 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20210423_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='finish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Finish Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
