# Generated by Django 3.1.1 on 2021-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20210423_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CampaignsList',
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='description',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_body',
            field=models.TextField(default='Ola', help_text='Write your email here'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='list',
            field=models.CharField(choices=[('List A', 'List A'), ('List B', 'List B'), ('List C', 'List C')], default='List A', max_length=12),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Completed', max_length=12),
        ),
    ]
