# Generated by Django 3.1.1 on 2021-04-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20210426_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
