# Generated by Django 3.2 on 2021-04-26 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0010_alter_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('filepath', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('information', models.CharField(choices=[('bar chart spam filter', 'bar chart spam filter'), ('bar chart opened', 'bar chart opened'), ('bar chart clicked', 'bar chart clicked')], default='bar chart spam filter', max_length=55)),
                ('id_campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
